# Generated by Django 2.1.5 on 2019-01-31 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190131_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='upload_at',
            new_name='updated_at',
        ),
    ]
