# Generated by Django 2.1.8 on 2019-04-10 05:09

from django.db import migrations
import imagekit.models.fields
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190409_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=posts.models.post_image_path),
        ),
    ]
